<?php

namespace KitWebBundle\Repository;

/**
 * WebAppealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebAppealRepository extends \Doctrine\ORM\EntityRepository
{
}
