<?php

namespace KitWebBundle\Repository;

/**
 * WebReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebReportRepository extends \Doctrine\ORM\EntityRepository
{
}
