kit_rbac_user:
    path:     /
    defaults: { _controller: RbacBundle:Default:index}
kit_rbac_user_add:
    path:     /add
    defaults: { _controller: RbacBundle:Default:add }
kit_rbac_user_delete:
    path:     /del
    defaults: { _controller: RbacBundle:Default:delete }
kit_rbac_user_update:
    path:     /update
    defaults: { _controller: RbacBundle:Default:update }
    
kit_rbac_role:
    path:     /role
    defaults: { _controller: RbacBundle:Role:index }
kit_rbac_role_add:
    path:     /role/add
    defaults: { _controller: RbacBundle:Role:add }
kit_rbac_role_del:
    path:     /role/del
    defaults: { _controller: RbacBundle:Role:del }
