# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
# security:

#     # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
#     providers:
#         in_memory:
#             memory: ~

#     firewalls:
#         # disables authentication for assets and the profiler, adapt it according to your needs
#         dev:
#             pattern: ^/(_(profiler|wdt)|css|images|js)/
#             security: false

#         main:
#             anonymous: ~
#             # activate different ways to authenticate

#             # http_basic: ~
#             # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

#             # form_login: ~
#             # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
security:
    encoders:
        KitWebBundle\Entity\WebUser: bcrypt
        #FOS\UserBundle\Model\UserInterface: bcrypt
        KitRbacBundle\Entity\User:
            algorithm: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        database_web_users:
            entity: {class: KitWebBundle:WebUser, property: email }
        # fos_userbundle:
        #     id: fos_user.user_provider.username
        database_admin_users:
            entity:
                class: KitRbacBundle:User
                property: username
    firewalls:
        admin_firewalls:
            pattern:   ^/admin
            anonymous: ~
            provider: database_admin_users
            guard:
                authenticators:
                    - kit_admin.admin_form_login_authenticator
            form_login:
                login_path: kit_admin_login
                check_path: kit_admin_login
                default_target_path: /admin
                username_parameter: _username
                password_parameter: _password
                failure_path: kit_admin_login
            logout:
                path: kit_admin_logout
                target: kit_admin_login
        main:
            pattern: ^/
            anonymous: ~
            guard:
                authenticators:
                    - kit_web.form_login_authenticator
            #form_login:
            #    login_path: kit_web_login
            #    check_path: kit_web_login_check
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/user, role: ROLE_USER }
