KitAdminBundle\Entity\UserTest:
    type: entity
    table: user_test
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
        mobile:
            type: string
            nullable: false
            length: 11
            options:
                fixed: true
        status:
            type: smallint
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
