<?php

namespace KitAdminBundle\Repository;

/**
 * AdminRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
