<?php
namespace KitAdminBundle\Repository;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get all admins
     *
     * @return multitype:
     */
    public function getAllAdmins()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a, g FROM KitAdminBundle:Admin a
                        JOIN a.group g')
            ->getResult();
    }

    /**
     * Get admin by name
     */
    public function getAdminByName($name)
    {
        return $this->findOneBy([
            'name' => $name
        ]);
    }
}
