<?php

namespace KitAdminBundle\Repository;

/**
 * BasicSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasicSettingRepository extends \Doctrine\ORM\EntityRepository
{
    public function basicRepo(){
        /**
         * @var $basic \KitAdminBundle\Entity\BasicSetting
         */
        $basic = $this->createQueryBuilder('b')
        ->getQuery()
        ->getArrayResult();
        $basicArr =[];
        foreach ($basic as $k => $v)
        {
            $basicArr['logo'] = $v['logo']; //网站LOGO
            $basicArr['sitename'] = $v['sitename'];  //网站名称
            $basicArr['keywords'] = $v['keywords'];   //网站关键字
            $basicArr['description'] = $v['description'];    //网站描述
            $basicArr['copyright'] = $v['copyright'];    //版权信息
            $basicArr['contact'] = $v['contact'];    //联系方式
            $basicArr['icp'] = $v['icp'];    //ICP备案号
            $basicArr['code'] = $v['code'];  //统计代码
            $basicArr['other'] = $v['other'];    //其他内容
        }
      
        return $basicArr;
    }
}
