<?php

namespace KitAdminBundle\Repository;

/**
 * ConfigCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
