<?php

namespace KitRbacBundle\Repository;

/**
 * AccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessRepository extends \Doctrine\ORM\EntityRepository
{
}
