<?php

namespace KitRbacBundle\Repository;

/**
 * MenuAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
