<?php

namespace KitRbacBundle\Repository;

/**
 * RoleAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
