<?php
namespace KitNewsBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{

    public function getList()
    {
        return $this->createQueryBuilder('n')
            ->orderBy('n.id', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function getListByCategory($cid)
    {
        return $this->createQueryBuilder('n')
            ->join('n.category', 'c')
            ->where('c.id = :cid')
        // ->select('u.id', 'u.username', 'u.createAt', 'u.updateAt', 'r.rolename')
        // ->where('u.status = ?0')
        // ->setParameter(0, 1) // key, The parameter position or name
            ->orderBy('n.id', 'DESC')
            ->orWhere('c.parentId =:cid')
            ->setParameter('cid', $cid)
            ->getQuery()
            ->getResult();
    }
    
    public function getToutiao($level)
    {
        return $this->createQueryBuilder('n')
        ->where('n.level = :level')
        // ->select('u.id', 'u.username', 'u.createAt', 'u.updateAt', 'r.rolename')
        // ->where('u.status = ?0')
        // ->setParameter(0, 1) // key, The parameter position or name
        ->orderBy('n.id', 'DESC')
        ->setParameter('level', $level)
        ->getQuery()
        ->getOneOrNullResult();
    }
    /**
     * 获取相关的新闻，自带分页
     */
    public function getListPage($cid, $offset = null, $limit = null, $level = null)
    {
        $qb = $this->createQueryBuilder('n')
            ->join('n.category', 'c')
            ->orderBy('n.id', 'DESC');
        if (false === is_null($cid)) {
            $qb->where('c.id = :cid')
                ->orWhere('c.parentId =:cid')
                ->setParameter('cid', $cid);
        }
        
        if (false === is_null($level)) {
            $qb->andWhere('n.level = :level')->setParameter('level', $level);
        }
        if (false === is_null($offset)) {
            $qb->setFirstResult($offset);
        }
        
        if (false === is_null($limit)) {
            $qb->setMaxResults($limit);
        }
        return $qb->getQuery()->getResult();
    }

    /**
     */
    public function getPrevAndNext($id)
    {
        $prev = $this->getEntityManager()
            ->createQuery('SELECT n FROM KitNewsBundle:News n WHERE n.id < :id ORDER BY n.id DESC')
            ->setParameter('id', $id)
            ->setMaxResults(1)
            ->getResult();
        $next = $this->getEntityManager()
            ->createQuery('SELECT n FROM KitNewsBundle:News n WHERE n.id > :id ORDER BY n.id ASC')
            ->setParameter('id', $id)
            ->setMaxResults(1)
            ->getResult();
        return [
            'prev' => empty($prev) ? [] : $prev[0],
            'next' => empty($next) ? [] : $next[0]
        ];
    }
}
