<?php

namespace KitNewsBundle\Repository;

/**
 * NewsContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsContentRepository extends \Doctrine\ORM\EntityRepository
{
}
