kit_api_v1:
    resource: "@KitApiBundle/Resources/config/routing/v1.yml"
    prefix:   /
    condition: "request.attributes.get('version') == 1"
kit_api_v2:
    resource: "@KitApiBundle/Resources/config/routing/v2.yml"
    prefix:   /
    condition: "request.attributes.get('version') == 2"
kit_api_homepage:
    path:     /
    defaults: { _controller: KitApiBundle:Default:index }
kit_api_pay:
    path:     /pay
    defaults: { _controller: KitApiBundle:Pay:index }