services:
#    kit_api.example:
#        class: KitApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    kit_api.api_version_listener:
        class: KitApiBundle\EventListener\ApiVersionListener
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
