services:
#    kit_pay.example:
#        class: Kit\Bundle\KitPayBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    kit_pay.example:
        class: Kit\Bundle\KitPayBundle\PaymentService
        arguments: ["@service_id", "plain_value", "%parameter%"]
